[env:fysetc_sd_wifi]
platform = espressif8266
board = esp8285
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    greiman/SdFat @ ^2.1.2
    ESP8266Ping
