[env:fystec_sd_wifi]
platform = espressif8266
board = esp8285
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs ; Не используется для хранения, но требуется для платформы
lib_deps =
build_flags = 
    -D HTTP_PORT=80
